### ISSUE TITLE
只能输整数

### ISSUE THREAD

**Issue by SBeator** [lijinke666/javascript-demos#1]
https://github.com/lijinke666/javascript-demos/blob/db8b938edeea334a5241814879e4290b15bd8e24/%E5%8F%AA%E8%83%BD%E8%BE%93%E5%85%A5%E6%95%B4%E6%95%B0/index.js#L1

```
const reg = /^-?(0|[1-9][0-9]*)?$/

console.log(reg.test('-'))   // true
```

'-'也会返回true，是你想要的吗？

**Comment by lijinke666** [comment]
@SBeator 哈哈 测试覆盖率不全哈, 确实有问题

**Comment by lijinke666** [comment]
有更优雅的解法吗

**Comment by lijinke666** [comment]
但是当时的场景是一个 input 要阻止它输入 非数字, 所以 只输入 `-` 的情况 也让他输入, 在这种场景下 正则是对的, 不过单独提出来确实是有问题
